/**
 * 国税庁「類似業種比準価額計算上の業種目及び業種目別株価等について」
 *
 * ⚠️ 定期更新が必要なデータ
 * - 出典: https://www.nta.go.jp/law/tsutatsu/kobetsu/hyoka/
 * - 新年度分: 毎年7〜8月頃公表（前年の確定値）
 * - 月次株価: 毎月公表（2ヶ月ごとの場合あり）
 * - 保存年数: 相続税申告期限（相続開始から10ヶ月）を考慮し過去5年分を推奨
 *
 * 階層構造:
 * - 大分類のみ: mediumCategory = "（全体）", minorCategory = "（全体）"
 * - 中分類まで: minorCategory = "（全体）"
 * - 3階層すべて: 各フィールドに実際の名称
 *
 * フィールド説明:
 * - A: 前年の年平均株価（通達182条で使用する「前年の株価」）
 * - B_prime: 1株当たり年配当金額（類似業種の標本会社平均）
 * - C_prime: 1株当たり年利益金額
 * - D_prime: 1株当たり純資産価額
 * - monthlyA: 当年の月次株価（「直前3か月」計算に使用）
 */

export interface SimilarIndustryDataRow {
  majorCategory: string
  mediumCategory: string
  minorCategory: string
  no: number
  /** 前年の年平均株価（通達182条①） */
  A: number
  /** 1株当たり年配当金額 */
  B_prime: number
  /** 1株当たり年利益金額 */
  C_prime: number
  /** 1株当たり純資産価額 */
  D_prime: number
  /** 当年の月次株価 { "1月": xxx, "2月": xxx, ... } */
  monthlyA?: Record<string, number>
  /** 評価年（保存時に動的付加される） */
  year?: string
}

export interface SimilarIndustryDatabase {
  [year: string]: SimilarIndustryDataRow[]
}

// ============================================================
// 令和7年分（2025年）- 115業種
// 出典: https://www.nta.go.jp/law/tsutatsu/kobetsu/hyoka/r07/2506/index.htm
// A = 前年（令和6年）の年平均株価
// monthlyA: 令和7年1月・2月分のみ公表済み（令和8年4月時点）
// 残月は国税庁ウェブサイトから順次取得・追加すること
// ============================================================
const reiwa7Data: SimilarIndustryDataRow[] = [
  // 建設業
  {
    no: 1,
    majorCategory: '建設業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 405,
    B_prime: 11.2,
    C_prime: 56,
    D_prime: 531,
    monthlyA: { '1月': 450, '2月': 463 },
  },
  {
    no: 2,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: '（全体）',
    A: 384,
    B_prime: 11.0,
    C_prime: 56,
    D_prime: 528,
    monthlyA: { '1月': 409, '2月': 418 },
  },
  {
    no: 3,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: '建築工事業（木造建築工事業を除く）',
    A: 471,
    B_prime: 15.0,
    C_prime: 88,
    D_prime: 608,
    monthlyA: { '1月': 516, '2月': 526 },
  },
  {
    no: 4,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: 'その他の総合工事業',
    A: 361,
    B_prime: 9.9,
    C_prime: 47,
    D_prime: 507,
    monthlyA: { '1月': 381, '2月': 389 },
  },
  {
    no: 5,
    majorCategory: '建設業',
    mediumCategory: '職別工事業',
    minorCategory: '（全体）',
    A: 470,
    B_prime: 13.7,
    C_prime: 54,
    D_prime: 570,
    monthlyA: { '1月': 479, '2月': 506 },
  },
  {
    no: 6,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: '（全体）',
    A: 443,
    B_prime: 11.0,
    C_prime: 60,
    D_prime: 540,
    monthlyA: { '1月': 549, '2月': 568 },
  },
  {
    no: 7,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: '電気工事業',
    A: 411,
    B_prime: 9.3,
    C_prime: 50,
    D_prime: 575,
    monthlyA: { '1月': 495, '2月': 525 },
  },
  {
    no: 8,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: 'その他の設備工事業',
    A: 462,
    B_prime: 12.0,
    C_prime: 67,
    D_prime: 518,
    monthlyA: { '1月': 582, '2月': 594 },
  },
  // 製造業
  {
    no: 9,
    majorCategory: '製造業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 438,
    B_prime: 9.2,
    C_prime: 46,
    D_prime: 434,
  },
  {
    no: 10,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: '（全体）',
    A: 665,
    B_prime: 8.4,
    C_prime: 45,
    D_prime: 451,
  },
  {
    no: 11,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: '畜産食料品製造業',
    A: 453,
    B_prime: 8.2,
    C_prime: 44,
    D_prime: 362,
  },
  {
    no: 12,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: 'パン・菓子製造業',
    A: 1508,
    B_prime: 8.4,
    C_prime: 44,
    D_prime: 587,
  },
  {
    no: 13,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: 'その他の食料品製造業',
    A: 524,
    B_prime: 8.5,
    C_prime: 45,
    D_prime: 444,
  },
  {
    no: 14,
    majorCategory: '製造業',
    mediumCategory: '飲料・たばこ・飼料製造業',
    minorCategory: '（全体）',
    A: 423,
    B_prime: 7.8,
    C_prime: 32,
    D_prime: 337,
  },
  {
    no: 15,
    majorCategory: '製造業',
    mediumCategory: '繊維工業',
    minorCategory: '（全体）',
    A: 285,
    B_prime: 6.1,
    C_prime: 30,
    D_prime: 367,
  },
  {
    no: 16,
    majorCategory: '製造業',
    mediumCategory: 'パルプ・紙・紙加工品製造業',
    minorCategory: '（全体）',
    A: 176,
    B_prime: 4.2,
    C_prime: 28,
    D_prime: 321,
  },
  {
    no: 17,
    majorCategory: '製造業',
    mediumCategory: '印刷・同関連業',
    minorCategory: '（全体）',
    A: 252,
    B_prime: 5.6,
    C_prime: 33,
    D_prime: 379,
  },
  {
    no: 18,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '（全体）',
    A: 463,
    B_prime: 10.5,
    C_prime: 38,
    D_prime: 403,
  },
  {
    no: 19,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '有機化学工業製品製造業',
    A: 358,
    B_prime: 8.3,
    C_prime: 42,
    D_prime: 361,
  },
  {
    no: 20,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '油脂加工製品・石けん・合成洗剤・界面活性剤・塗料製造業',
    A: 248,
    B_prime: 5.6,
    C_prime: 32,
    D_prime: 338,
  },
  {
    no: 21,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '医薬品製造業',
    A: 864,
    B_prime: 19.5,
    C_prime: 63,
    D_prime: 545,
  },
  {
    no: 22,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: 'その他の化学工業',
    A: 387,
    B_prime: 8.8,
    C_prime: 29,
    D_prime: 375,
  },
  {
    no: 23,
    majorCategory: '製造業',
    mediumCategory: 'プラスチック製品製造業',
    minorCategory: '（全体）',
    A: 359,
    B_prime: 8.8,
    C_prime: 39,
    D_prime: 424,
  },
  {
    no: 24,
    majorCategory: '製造業',
    mediumCategory: 'ゴム製品製造業',
    minorCategory: '（全体）',
    A: 482,
    B_prime: 15.8,
    C_prime: 74,
    D_prime: 625,
  },
  {
    no: 25,
    majorCategory: '製造業',
    mediumCategory: '窯業・土石製品製造業',
    minorCategory: '（全体）',
    A: 406,
    B_prime: 10.4,
    C_prime: 62,
    D_prime: 434,
  },
  {
    no: 26,
    majorCategory: '製造業',
    mediumCategory: '窯業・土石製品製造業',
    minorCategory: 'セメント・同製品製造業',
    A: 350,
    B_prime: 7.1,
    C_prime: 51,
    D_prime: 370,
  },
  {
    no: 27,
    majorCategory: '製造業',
    mediumCategory: '窯業・土石製品製造業',
    minorCategory: 'その他の窯業・土石製品製造業',
    A: 433,
    B_prime: 11.9,
    C_prime: 68,
    D_prime: 465,
  },
  {
    no: 28,
    majorCategory: '製造業',
    mediumCategory: '鉄鋼業',
    minorCategory: '（全体）',
    A: 297,
    B_prime: 9.4,
    C_prime: 53,
    D_prime: 465,
  },
  {
    no: 29,
    majorCategory: '製造業',
    mediumCategory: '非鉄金属製造業',
    minorCategory: '（全体）',
    A: 288,
    B_prime: 7.4,
    C_prime: 34,
    D_prime: 389,
  },
  {
    no: 30,
    majorCategory: '製造業',
    mediumCategory: '金属製品製造業',
    minorCategory: '（全体）',
    A: 412,
    B_prime: 10.1,
    C_prime: 52,
    D_prime: 585,
  },
  {
    no: 31,
    majorCategory: '製造業',
    mediumCategory: '金属製品製造業',
    minorCategory: '建設用・建築用金属製品製造業',
    A: 241,
    B_prime: 5.7,
    C_prime: 40,
    D_prime: 389,
  },
  {
    no: 32,
    majorCategory: '製造業',
    mediumCategory: '金属製品製造業',
    minorCategory: 'その他の金属製品製造業',
    A: 472,
    B_prime: 11.6,
    C_prime: 56,
    D_prime: 653,
  },
  {
    no: 33,
    majorCategory: '製造業',
    mediumCategory: 'はん用機械器具製造業',
    minorCategory: '（全体）',
    A: 478,
    B_prime: 10.4,
    C_prime: 68,
    D_prime: 485,
  },
  {
    no: 34,
    majorCategory: '製造業',
    mediumCategory: '生産用機械器具製造業',
    minorCategory: '（全体）',
    A: 453,
    B_prime: 9.5,
    C_prime: 44,
    D_prime: 368,
  },
  {
    no: 35,
    majorCategory: '製造業',
    mediumCategory: '生産用機械器具製造業',
    minorCategory: '金属加工機械製造業',
    A: 333,
    B_prime: 8.9,
    C_prime: 38,
    D_prime: 357,
  },
  {
    no: 36,
    majorCategory: '製造業',
    mediumCategory: '生産用機械器具製造業',
    minorCategory: 'その他の生産用機械器具製造業',
    A: 491,
    B_prime: 9.6,
    C_prime: 46,
    D_prime: 372,
  },
  {
    no: 37,
    majorCategory: '製造業',
    mediumCategory: '業務用機械器具製造業',
    minorCategory: '（全体）',
    A: 503,
    B_prime: 9.4,
    C_prime: 59,
    D_prime: 419,
  },
  {
    no: 38,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: '（全体）',
    A: 475,
    B_prime: 8.6,
    C_prime: 44,
    D_prime: 376,
  },
  {
    no: 39,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: '電子部品製造業',
    A: 564,
    B_prime: 10.4,
    C_prime: 43,
    D_prime: 450,
  },
  {
    no: 40,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: '電子回路製造業',
    A: 253,
    B_prime: 3.4,
    C_prime: 24,
    D_prime: 180,
  },
  {
    no: 41,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: 'その他の電子部品・デバイス・電子回路製造業',
    A: 498,
    B_prime: 9.2,
    C_prime: 50,
    D_prime: 397,
  },
  {
    no: 42,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: '（全体）',
    A: 691,
    B_prime: 10.1,
    C_prime: 51,
    D_prime: 501,
  },
  {
    no: 43,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: '発電用・送電用・配電用電気機械器具製造業',
    A: 1209,
    B_prime: 17.8,
    C_prime: 102,
    D_prime: 937,
  },
  {
    no: 44,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: '電気計測器製造業',
    A: 385,
    B_prime: 7.3,
    C_prime: 32,
    D_prime: 244,
  },
  {
    no: 45,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: 'その他の電気機械器具製造業',
    A: 637,
    B_prime: 8.1,
    C_prime: 39,
    D_prime: 454,
  },
  {
    no: 46,
    majorCategory: '製造業',
    mediumCategory: '情報通信機械器具製造業',
    minorCategory: '（全体）',
    A: 318,
    B_prime: 8.8,
    C_prime: 39,
    D_prime: 368,
  },
  {
    no: 47,
    majorCategory: '製造業',
    mediumCategory: '輸送用機械器具製造業',
    minorCategory: '（全体）',
    A: 361,
    B_prime: 10.2,
    C_prime: 55,
    D_prime: 591,
  },
  {
    no: 48,
    majorCategory: '製造業',
    mediumCategory: '輸送用機械器具製造業',
    minorCategory: '自動車・同附属品製造業',
    A: 355,
    B_prime: 11.2,
    C_prime: 59,
    D_prime: 626,
  },
  {
    no: 49,
    majorCategory: '製造業',
    mediumCategory: '輸送用機械器具製造業',
    minorCategory: 'その他の輸送用機械器具製造業',
    A: 390,
    B_prime: 5.8,
    C_prime: 35,
    D_prime: 435,
  },
  {
    no: 50,
    majorCategory: '製造業',
    mediumCategory: 'その他の製造業',
    minorCategory: '（全体）',
    A: 369,
    B_prime: 8.4,
    C_prime: 37,
    D_prime: 365,
  },
  // 電気・ガス・熱供給・水道業
  {
    no: 51,
    majorCategory: '電気・ガス・熱供給・水道業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 544,
    B_prime: 6.8,
    C_prime: 56,
    D_prime: 450,
  },
  // 情報通信業
  {
    no: 52,
    majorCategory: '情報通信業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 777,
    B_prime: 9.7,
    C_prime: 54,
    D_prime: 307,
  },
  {
    no: 53,
    majorCategory: '情報通信業',
    mediumCategory: '情報サービス業',
    minorCategory: '（全体）',
    A: 858,
    B_prime: 12.3,
    C_prime: 64,
    D_prime: 341,
  },
  {
    no: 54,
    majorCategory: '情報通信業',
    mediumCategory: '情報サービス業',
    minorCategory: 'ソフトウェア業',
    A: 886,
    B_prime: 12.4,
    C_prime: 64,
    D_prime: 326,
  },
  {
    no: 55,
    majorCategory: '情報通信業',
    mediumCategory: '情報サービス業',
    minorCategory: '情報処理・提供サービス業',
    A: 807,
    B_prime: 12.2,
    C_prime: 65,
    D_prime: 343,
  },
  {
    no: 56,
    majorCategory: '情報通信業',
    mediumCategory: 'インターネット附随サービス業',
    minorCategory: '（全体）',
    A: 695,
    B_prime: 6.2,
    C_prime: 38,
    D_prime: 195,
  },
  {
    no: 57,
    majorCategory: '情報通信業',
    mediumCategory: '映像・音声・文字情報制作業',
    minorCategory: '（全体）',
    A: 555,
    B_prime: 5.5,
    C_prime: 43,
    D_prime: 313,
  },
  {
    no: 58,
    majorCategory: '情報通信業',
    mediumCategory: 'その他の情報通信業',
    minorCategory: '（全体）',
    A: 626,
    B_prime: 7.0,
    C_prime: 49,
    D_prime: 669,
  },
  // 運輸業、郵便業
  {
    no: 59,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 345,
    B_prime: 8.6,
    C_prime: 52,
    D_prime: 506,
  },
  {
    no: 60,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '道路貨物運送業',
    minorCategory: '（全体）',
    A: 350,
    B_prime: 8.8,
    C_prime: 50,
    D_prime: 437,
  },
  {
    no: 61,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '水運業',
    minorCategory: '（全体）',
    A: 314,
    B_prime: 17.2,
    C_prime: 77,
    D_prime: 597,
  },
  {
    no: 62,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '運輸に附帯するサービス業',
    minorCategory: '（全体）',
    A: 328,
    B_prime: 9.2,
    C_prime: 46,
    D_prime: 615,
  },
  {
    no: 63,
    majorCategory: '運輸業、郵便業',
    mediumCategory: 'その他の運輸業、郵便業',
    minorCategory: '（全体）',
    A: 361,
    B_prime: 5.4,
    C_prime: 50,
    D_prime: 466,
  },
  // 卸売業
  {
    no: 64,
    majorCategory: '卸売業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 507,
    B_prime: 12.0,
    C_prime: 65,
    D_prime: 539,
  },
  {
    no: 65,
    majorCategory: '卸売業',
    mediumCategory: '各種商品卸売業',
    minorCategory: '（全体）',
    A: 624,
    B_prime: 20.3,
    C_prime: 95,
    D_prime: 666,
  },
  {
    no: 66,
    majorCategory: '卸売業',
    mediumCategory: '繊維・衣服等卸売業',
    minorCategory: '（全体）',
    A: 249,
    B_prime: 6.8,
    C_prime: 39,
    D_prime: 501,
  },
  {
    no: 67,
    majorCategory: '卸売業',
    mediumCategory: '飲食料品卸売業',
    minorCategory: '（全体）',
    A: 773,
    B_prime: 9.8,
    C_prime: 75,
    D_prime: 525,
  },
  {
    no: 68,
    majorCategory: '卸売業',
    mediumCategory: '飲食料品卸売業',
    minorCategory: '農畜産物・水産物卸売業',
    A: 192,
    B_prime: 3.2,
    C_prime: 31,
    D_prime: 281,
  },
  {
    no: 69,
    majorCategory: '卸売業',
    mediumCategory: '飲食料品卸売業',
    minorCategory: '食料・飲料卸売業',
    A: 964,
    B_prime: 14.6,
    C_prime: 107,
    D_prime: 728,
  },
  {
    no: 70,
    majorCategory: '卸売業',
    mediumCategory: '建築材料、鉱物・金属材料等卸売業',
    minorCategory: '（全体）',
    A: 417,
    B_prime: 12.9,
    C_prime: 71,
    D_prime: 600,
  },
  {
    no: 71,
    majorCategory: '卸売業',
    mediumCategory: '建築材料、鉱物・金属材料等卸売業',
    minorCategory: '化学製品卸売業',
    A: 559,
    B_prime: 17.1,
    C_prime: 86,
    D_prime: 801,
  },
  {
    no: 72,
    majorCategory: '卸売業',
    mediumCategory: '建築材料、鉱物・金属材料等卸売業',
    minorCategory: 'その他の建築材料、鉱物・金属材料等卸売業',
    A: 377,
    B_prime: 11.7,
    C_prime: 67,
    D_prime: 544,
  },
  {
    no: 73,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: '（全体）',
    A: 517,
    B_prime: 14.3,
    C_prime: 66,
    D_prime: 563,
  },
  {
    no: 74,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: '産業機械器具卸売業',
    A: 407,
    B_prime: 11.1,
    C_prime: 51,
    D_prime: 480,
  },
  {
    no: 75,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: '電気機械器具卸売業',
    A: 607,
    B_prime: 16.6,
    C_prime: 72,
    D_prime: 641,
  },
  {
    no: 76,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: 'その他の機械器具卸売業',
    A: 537,
    B_prime: 15.7,
    C_prime: 81,
    D_prime: 560,
  },
  {
    no: 77,
    majorCategory: '卸売業',
    mediumCategory: 'その他の卸売業',
    minorCategory: '（全体）',
    A: 416,
    B_prime: 8.6,
    C_prime: 52,
    D_prime: 441,
  },
  // 小売業
  {
    no: 78,
    majorCategory: '小売業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 541,
    B_prime: 8.7,
    C_prime: 56,
    D_prime: 379,
  },
  {
    no: 79,
    majorCategory: '小売業',
    mediumCategory: '各種商品小売業',
    minorCategory: '（全体）',
    A: 680,
    B_prime: 8.6,
    C_prime: 67,
    D_prime: 524,
  },
  {
    no: 80,
    majorCategory: '小売業',
    mediumCategory: '織物・衣服・身の回り品小売業',
    minorCategory: '（全体）',
    A: 944,
    B_prime: 15.4,
    C_prime: 88,
    D_prime: 485,
  },
  {
    no: 81,
    majorCategory: '小売業',
    mediumCategory: '飲食料品小売業',
    minorCategory: '（全体）',
    A: 387,
    B_prime: 5.6,
    C_prime: 42,
    D_prime: 299,
  },
  {
    no: 82,
    majorCategory: '小売業',
    mediumCategory: '機械器具小売業',
    minorCategory: '（全体）',
    A: 426,
    B_prime: 11.8,
    C_prime: 61,
    D_prime: 433,
  },
  {
    no: 83,
    majorCategory: '小売業',
    mediumCategory: 'その他の小売業',
    minorCategory: '（全体）',
    A: 500,
    B_prime: 7.5,
    C_prime: 48,
    D_prime: 310,
  },
  {
    no: 84,
    majorCategory: '小売業',
    mediumCategory: 'その他の小売業',
    minorCategory: '医薬品・化粧品小売業',
    A: 409,
    B_prime: 3.0,
    C_prime: 35,
    D_prime: 232,
  },
  {
    no: 85,
    majorCategory: '小売業',
    mediumCategory: 'その他の小売業',
    minorCategory: 'その他の小売業',
    A: 539,
    B_prime: 8.9,
    C_prime: 53,
    D_prime: 340,
  },
  {
    no: 86,
    majorCategory: '小売業',
    mediumCategory: '無店舗小売業',
    minorCategory: '（全体）',
    A: 354,
    B_prime: 4.6,
    C_prime: 33,
    D_prime: 199,
  },
  // 金融業、保険業
  {
    no: 87,
    majorCategory: '金融業、保険業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 292,
    B_prime: 6.3,
    C_prime: 41,
    D_prime: 308,
  },
  {
    no: 88,
    majorCategory: '金融業、保険業',
    mediumCategory: '銀行業',
    minorCategory: '（全体）',
    A: 124,
    B_prime: 3.4,
    C_prime: 18,
    D_prime: 309,
  },
  {
    no: 89,
    majorCategory: '金融業、保険業',
    mediumCategory: '金融商品取引業、商品先物取引業',
    minorCategory: '（全体）',
    A: 307,
    B_prime: 9.0,
    C_prime: 80,
    D_prime: 282,
  },
  {
    no: 90,
    majorCategory: '金融業、保険業',
    mediumCategory: 'その他の金融業、保険業',
    minorCategory: '（全体）',
    A: 629,
    B_prime: 10.3,
    C_prime: 58,
    D_prime: 326,
  },
  // 不動産業、物品賃貸業
  {
    no: 91,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 364,
    B_prime: 7.9,
    C_prime: 53,
    D_prime: 328,
  },
  {
    no: 92,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '不動産取引業',
    minorCategory: '（全体）',
    A: 269,
    B_prime: 7.1,
    C_prime: 47,
    D_prime: 271,
  },
  {
    no: 93,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '不動産賃貸業・管理業',
    minorCategory: '（全体）',
    A: 447,
    B_prime: 7.4,
    C_prime: 56,
    D_prime: 337,
  },
  {
    no: 94,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '物品賃貸業',
    minorCategory: '（全体）',
    A: 534,
    B_prime: 11.6,
    C_prime: 66,
    D_prime: 462,
  },
  // 専門・技術サービス業
  {
    no: 95,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 462,
    B_prime: 8.0,
    C_prime: 42,
    D_prime: 241,
  },
  {
    no: 96,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '専門サービス業',
    minorCategory: '（全体）',
    A: 621,
    B_prime: 9.0,
    C_prime: 56,
    D_prime: 225,
  },
  {
    no: 97,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '広告業',
    minorCategory: '（全体）',
    A: 535,
    B_prime: 10.0,
    C_prime: 45,
    D_prime: 245,
  },
  {
    no: 98,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '技術サービス業',
    minorCategory: '（全体）',
    A: 298,
    B_prime: 6.5,
    C_prime: 34,
    D_prime: 263,
  },
  {
    no: 99,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '技術サービス業',
    minorCategory: '土木建築サービス業',
    A: 277,
    B_prime: 7.4,
    C_prime: 38,
    D_prime: 243,
  },
  {
    no: 100,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '技術サービス業',
    minorCategory: 'その他の技術サービス業',
    A: 318,
    B_prime: 5.7,
    C_prime: 29,
    D_prime: 282,
  },
  // 宿泊業、飲食サービス業
  {
    no: 101,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 633,
    B_prime: 4.6,
    C_prime: 39,
    D_prime: 192,
  },
  {
    no: 102,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: '（全体）',
    A: 661,
    B_prime: 4.5,
    C_prime: 37,
    D_prime: 178,
  },
  {
    no: 103,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: '食堂、レストラン（専門料理店を除く）',
    A: 341,
    B_prime: 1.1,
    C_prime: 15,
    D_prime: 77,
  },
  {
    no: 104,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: '専門料理店',
    A: 695,
    B_prime: 4.9,
    C_prime: 38,
    D_prime: 189,
  },
  {
    no: 105,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: 'その他の飲食店',
    A: 762,
    B_prime: 5.5,
    C_prime: 44,
    D_prime: 208,
  },
  {
    no: 106,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: 'その他の宿泊業、飲食サービス業',
    minorCategory: '（全体）',
    A: 513,
    B_prime: 5.0,
    C_prime: 47,
    D_prime: 253,
  },
  // 生活関連サービス業、娯楽業
  {
    no: 107,
    majorCategory: '生活関連サービス業、娯楽業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 773,
    B_prime: 6.1,
    C_prime: 44,
    D_prime: 269,
  },
  {
    no: 108,
    majorCategory: '生活関連サービス業、娯楽業',
    mediumCategory: '生活関連サービス業',
    minorCategory: '（全体）',
    A: 246,
    B_prime: 3.3,
    C_prime: 33,
    D_prime: 175,
  },
  {
    no: 109,
    majorCategory: '生活関連サービス業、娯楽業',
    mediumCategory: '娯楽業',
    minorCategory: '（全体）',
    A: 1438,
    B_prime: 9.5,
    C_prime: 58,
    D_prime: 388,
  },
  // 教育、学習支援業
  {
    no: 110,
    majorCategory: '教育、学習支援業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 534,
    B_prime: 10.3,
    C_prime: 41,
    D_prime: 215,
  },
  // 医療、福祉
  {
    no: 111,
    majorCategory: '医療、福祉',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 483,
    B_prime: 6.7,
    C_prime: 41,
    D_prime: 239,
  },
  // サービス業（他に分類されないもの）
  {
    no: 112,
    majorCategory: 'サービス業（他に分類されないもの）',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 952,
    B_prime: 17.8,
    C_prime: 86,
    D_prime: 441,
  },
  {
    no: 113,
    majorCategory: 'サービス業（他に分類されないもの）',
    mediumCategory: '職業紹介・労働者派遣業',
    minorCategory: '（全体）',
    A: 1235,
    B_prime: 21.2,
    C_prime: 117,
    D_prime: 467,
  },
  {
    no: 114,
    majorCategory: 'サービス業（他に分類されないもの）',
    mediumCategory: 'その他の事業サービス業',
    minorCategory: '（全体）',
    A: 756,
    B_prime: 15.4,
    C_prime: 65,
    D_prime: 424,
  },
  // その他の産業
  {
    no: 115,
    majorCategory: 'その他の産業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 515,
    B_prime: 9.4,
    C_prime: 51,
    D_prime: 395,
  },
]

// ============================================================
// 令和6年分（2024年）- 113業種
// 出典: https://www.nta.go.jp/law/tsutatsu/kobetsu/hyoka/r06/2406/index.htm
// A = 前年（令和5年）の年平均株価
// monthlyA: 令和6年11月・12月分のみ掲載（残月は国税庁ウェブサイトから追加）
// ============================================================
const reiwa6Data: SimilarIndustryDataRow[] = [
  // 建設業（令和6年は設備工事業に3小分類あり）
  {
    no: 1,
    majorCategory: '建設業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 371,
    B_prime: 10.6,
    C_prime: 51,
    D_prime: 467,
    monthlyA: { '11月': 393, '12月': 397 },
  },
  {
    no: 2,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: '（全体）',
    A: 305,
    B_prime: 9.0,
    C_prime: 46,
    D_prime: 411,
    monthlyA: { '11月': 323, '12月': 324 },
  },
  {
    no: 3,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: '建築工事業（木造建築工事業を除く）',
    A: 368,
    B_prime: 11.1,
    C_prime: 73,
    D_prime: 458,
    monthlyA: { '11月': 376, '12月': 373 },
  },
  {
    no: 4,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: 'その他の総合工事業',
    A: 288,
    B_prime: 8.4,
    C_prime: 39,
    D_prime: 398,
    monthlyA: { '11月': 309, '12月': 311 },
  },
  {
    no: 5,
    majorCategory: '建設業',
    mediumCategory: '職別工事業',
    minorCategory: '（全体）',
    A: 447,
    B_prime: 13.0,
    C_prime: 50,
    D_prime: 540,
    monthlyA: { '11月': 449, '12月': 452 },
  },
  {
    no: 6,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: '（全体）',
    A: 498,
    B_prime: 13.6,
    C_prime: 63,
    D_prime: 578,
    monthlyA: { '11月': 535, '12月': 544 },
  },
  {
    no: 7,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: '電気工事業',
    A: 340,
    B_prime: 9.0,
    C_prime: 39,
    D_prime: 589,
    monthlyA: { '11月': 373, '12月': 388 },
  },
  {
    no: 8,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: '電気通信・信号装置工事業',
    A: 270,
    B_prime: 6.8,
    C_prime: 30,
    D_prime: 248,
    monthlyA: { '11月': 287, '12月': 286 },
  },
  {
    no: 9,
    majorCategory: '建設業',
    mediumCategory: '設備工事業',
    minorCategory: 'その他の設備工事業',
    A: 651,
    B_prime: 18.2,
    C_prime: 86,
    D_prime: 658,
    monthlyA: { '11月': 696, '12月': 704 },
  },
  // 製造業
  {
    no: 10,
    majorCategory: '製造業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 400,
    B_prime: 7.8,
    C_prime: 40,
    D_prime: 377,
    monthlyA: { '11月': 421, '12月': 424 },
  },
  {
    no: 11,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: '（全体）',
    A: 611,
    B_prime: 7.6,
    C_prime: 33,
    D_prime: 426,
    monthlyA: { '11月': 650, '12月': 645 },
  },
  {
    no: 12,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: '畜産食料品製造業',
    A: 458,
    B_prime: 8.0,
    C_prime: 34,
    D_prime: 351,
    monthlyA: { '11月': 460, '12月': 453 },
  },
  {
    no: 13,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: 'パン・菓子製造業',
    A: 1501,
    B_prime: 8.2,
    C_prime: 42,
    D_prime: 623,
    monthlyA: { '11月': 1578, '12月': 1563 },
  },
  {
    no: 14,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: 'その他の食料品製造業',
    A: 444,
    B_prime: 7.4,
    C_prime: 31,
    D_prime: 401,
    monthlyA: { '11月': 485, '12月': 482 },
  },
  {
    no: 15,
    majorCategory: '製造業',
    mediumCategory: '飲料・たばこ・飼料製造業',
    minorCategory: '（全体）',
    A: 400,
    B_prime: 6.9,
    C_prime: 26,
    D_prime: 343,
    monthlyA: { '11月': 436, '12月': 437 },
  },
  {
    no: 16,
    majorCategory: '製造業',
    mediumCategory: '繊維工業',
    minorCategory: '（全体）',
    A: 309,
    B_prime: 5.4,
    C_prime: 30,
    D_prime: 327,
    monthlyA: { '11月': 340, '12月': 340 },
  },
  {
    no: 17,
    majorCategory: '製造業',
    mediumCategory: 'パルプ・紙・紙加工品製造業',
    minorCategory: '（全体）',
    A: 166,
    B_prime: 4.1,
    C_prime: 21,
    D_prime: 303,
    monthlyA: { '11月': 178, '12月': 181 },
  },
  {
    no: 18,
    majorCategory: '製造業',
    mediumCategory: '印刷・同関連業',
    minorCategory: '（全体）',
    A: 217,
    B_prime: 4.7,
    C_prime: 28,
    D_prime: 327,
    monthlyA: { '11月': 222, '12月': 226 },
  },
  {
    no: 19,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '（全体）',
    A: 471,
    B_prime: 9.9,
    C_prime: 40,
    D_prime: 408,
    monthlyA: { '11月': 483, '12月': 485 },
  },
  {
    no: 20,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '有機化学工業製品製造業',
    A: 382,
    B_prime: 8.5,
    C_prime: 40,
    D_prime: 348,
    monthlyA: { '11月': 404, '12月': 405 },
  },
  {
    no: 21,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '油脂加工製品・石けん・合成洗剤・界面活性剤・塗料製造業',
    A: 220,
    B_prime: 5.2,
    C_prime: 22,
    D_prime: 331,
    monthlyA: { '11月': 234, '12月': 236 },
  },
  {
    no: 22,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: '医薬品製造業',
    A: 836,
    B_prime: 16.8,
    C_prime: 66,
    D_prime: 603,
    monthlyA: { '11月': 860, '12月': 873 },
  },
  {
    no: 23,
    majorCategory: '製造業',
    mediumCategory: '化学工業',
    minorCategory: 'その他の化学工業',
    A: 402,
    B_prime: 8.5,
    C_prime: 34,
    D_prime: 358,
    monthlyA: { '11月': 406, '12月': 403 },
  },
  {
    no: 24,
    majorCategory: '製造業',
    mediumCategory: 'プラスチック製品製造業',
    minorCategory: '（全体）',
    A: 217,
    B_prime: 5.7,
    C_prime: 28,
    D_prime: 307,
    monthlyA: { '11月': 228, '12月': 225 },
  },
  {
    no: 25,
    majorCategory: '製造業',
    mediumCategory: 'ゴム製品製造業',
    minorCategory: '（全体）',
    A: 484,
    B_prime: 15.1,
    C_prime: 61,
    D_prime: 587,
    monthlyA: { '11月': 529, '12月': 536 },
  },
  {
    no: 26,
    majorCategory: '製造業',
    mediumCategory: '窯業・土石製品製造業',
    minorCategory: '（全体）',
    A: 323,
    B_prime: 7.5,
    C_prime: 39,
    D_prime: 341,
    monthlyA: { '11月': 336, '12月': 338 },
  },
  {
    no: 27,
    majorCategory: '製造業',
    mediumCategory: '窯業・土石製品製造業',
    minorCategory: 'セメント・同製品製造業',
    A: 185,
    B_prime: 4.1,
    C_prime: 23,
    D_prime: 242,
    monthlyA: { '11月': 199, '12月': 208 },
  },
  {
    no: 28,
    majorCategory: '製造業',
    mediumCategory: '窯業・土石製品製造業',
    minorCategory: 'その他の窯業・土石製品製造業',
    A: 390,
    B_prime: 9.2,
    C_prime: 47,
    D_prime: 390,
    monthlyA: { '11月': 403, '12月': 401 },
  },
  {
    no: 29,
    majorCategory: '製造業',
    mediumCategory: '鉄鋼業',
    minorCategory: '（全体）',
    A: 264,
    B_prime: 6.5,
    C_prime: 51,
    D_prime: 413,
    monthlyA: { '11月': 296, '12月': 295 },
  },
  {
    no: 30,
    majorCategory: '製造業',
    mediumCategory: '非鉄金属製造業',
    minorCategory: '（全体）',
    A: 257,
    B_prime: 6.1,
    C_prime: 37,
    D_prime: 327,
    monthlyA: { '11月': 256, '12月': 248 },
  },
  {
    no: 31,
    majorCategory: '製造業',
    mediumCategory: '金属製品製造業',
    minorCategory: '（全体）',
    A: 229,
    B_prime: 5.9,
    C_prime: 32,
    D_prime: 367,
    monthlyA: { '11月': 236, '12月': 237 },
  },
  {
    no: 32,
    majorCategory: '製造業',
    mediumCategory: '金属製品製造業',
    minorCategory: '建設用・建築用金属製品製造業',
    A: 208,
    B_prime: 4.7,
    C_prime: 35,
    D_prime: 331,
    monthlyA: { '11月': 211, '12月': 213 },
  },
  {
    no: 33,
    majorCategory: '製造業',
    mediumCategory: '金属製品製造業',
    minorCategory: 'その他の金属製品製造業',
    A: 238,
    B_prime: 6.4,
    C_prime: 30,
    D_prime: 383,
    monthlyA: { '11月': 247, '12月': 247 },
  },
  {
    no: 34,
    majorCategory: '製造業',
    mediumCategory: 'はん用機械器具製造業',
    minorCategory: '（全体）',
    A: 368,
    B_prime: 8.4,
    C_prime: 48,
    D_prime: 408,
    monthlyA: { '11月': 394, '12月': 402 },
  },
  {
    no: 35,
    majorCategory: '製造業',
    mediumCategory: '生産用機械器具製造業',
    minorCategory: '（全体）',
    A: 462,
    B_prime: 8.2,
    C_prime: 47,
    D_prime: 319,
    monthlyA: { '11月': 496, '12月': 512 },
  },
  {
    no: 36,
    majorCategory: '製造業',
    mediumCategory: '生産用機械器具製造業',
    minorCategory: '金属加工機械製造業',
    A: 278,
    B_prime: 6.0,
    C_prime: 33,
    D_prime: 301,
    monthlyA: { '11月': 285, '12月': 281 },
  },
  {
    no: 37,
    majorCategory: '製造業',
    mediumCategory: '生産用機械器具製造業',
    minorCategory: 'その他の生産用機械器具製造業',
    A: 513,
    B_prime: 8.8,
    C_prime: 51,
    D_prime: 324,
    monthlyA: { '11月': 554, '12月': 575 },
  },
  {
    no: 38,
    majorCategory: '製造業',
    mediumCategory: '業務用機械器具製造業',
    minorCategory: '（全体）',
    A: 536,
    B_prime: 8.9,
    C_prime: 49,
    D_prime: 373,
    monthlyA: { '11月': 566, '12月': 591 },
  },
  {
    no: 39,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: '（全体）',
    A: 417,
    B_prime: 6.7,
    C_prime: 46,
    D_prime: 319,
    monthlyA: { '11月': 443, '12月': 450 },
  },
  {
    no: 40,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: '電子部品製造業',
    A: 414,
    B_prime: 7.2,
    C_prime: 45,
    D_prime: 362,
    monthlyA: { '11月': 458, '12月': 471 },
  },
  {
    no: 41,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: '電子回路製造業',
    A: 177,
    B_prime: 2.4,
    C_prime: 23,
    D_prime: 157,
    monthlyA: { '11月': 201, '12月': 205 },
  },
  {
    no: 42,
    majorCategory: '製造業',
    mediumCategory: '電子部品・デバイス・電子回路製造業',
    minorCategory: 'その他の電子部品・デバイス・電子回路製造業',
    A: 499,
    B_prime: 7.8,
    C_prime: 55,
    D_prime: 345,
    monthlyA: { '11月': 514, '12月': 518 },
  },
  {
    no: 43,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: '（全体）',
    A: 567,
    B_prime: 7.8,
    C_prime: 50,
    D_prime: 446,
    monthlyA: { '11月': 581, '12月': 564 },
  },
  {
    no: 44,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: '発電用・送電用・配電用電気機械器具製造業',
    A: 636,
    B_prime: 13.9,
    C_prime: 67,
    D_prime: 854,
    monthlyA: { '11月': 758, '12月': 740 },
  },
  {
    no: 45,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: '電気計測器製造業',
    A: 344,
    B_prime: 5.9,
    C_prime: 30,
    D_prime: 219,
    monthlyA: { '11月': 359, '12月': 361 },
  },
  {
    no: 46,
    majorCategory: '製造業',
    mediumCategory: '電気機械器具製造業',
    minorCategory: 'その他の電気機械器具製造業',
    A: 661,
    B_prime: 6.3,
    C_prime: 54,
    D_prime: 402,
    monthlyA: { '11月': 630, '12月': 603 },
  },
  {
    no: 47,
    majorCategory: '製造業',
    mediumCategory: '情報通信機械器具製造業',
    minorCategory: '（全体）',
    A: 352,
    B_prime: 8.8,
    C_prime: 40,
    D_prime: 411,
    monthlyA: { '11月': 371, '12月': 371 },
  },
  {
    no: 48,
    majorCategory: '製造業',
    mediumCategory: '輸送用機械器具製造業',
    minorCategory: '（全体）',
    A: 274,
    B_prime: 7.2,
    C_prime: 36,
    D_prime: 418,
    monthlyA: { '11月': 302, '12月': 292 },
  },
  {
    no: 49,
    majorCategory: '製造業',
    mediumCategory: '輸送用機械器具製造業',
    minorCategory: '自動車・同附属品製造業',
    A: 246,
    B_prime: 7.6,
    C_prime: 35,
    D_prime: 429,
    monthlyA: { '11月': 271, '12月': 260 },
  },
  {
    no: 50,
    majorCategory: '製造業',
    mediumCategory: '輸送用機械器具製造業',
    minorCategory: 'その他の輸送用機械器具製造業',
    A: 394,
    B_prime: 5.3,
    C_prime: 38,
    D_prime: 372,
    monthlyA: { '11月': 435, '12月': 432 },
  },
  {
    no: 51,
    majorCategory: '製造業',
    mediumCategory: 'その他の製造業',
    minorCategory: '（全体）',
    A: 397,
    B_prime: 8.5,
    C_prime: 41,
    D_prime: 364,
    monthlyA: { '11月': 412, '12月': 414 },
  },
  // 電気・ガス・熱供給・水道業
  {
    no: 52,
    majorCategory: '電気・ガス・熱供給・水道業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 650,
    B_prime: 6.8,
    C_prime: 43,
    D_prime: 404,
    monthlyA: { '11月': 470, '12月': 454 },
  },
  // 情報通信業
  {
    no: 53,
    majorCategory: '情報通信業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 721,
    B_prime: 8.6,
    C_prime: 50,
    D_prime: 285,
    monthlyA: { '11月': 715, '12月': 715 },
  },
  {
    no: 54,
    majorCategory: '情報通信業',
    mediumCategory: '情報サービス業',
    minorCategory: '（全体）',
    A: 792,
    B_prime: 9.6,
    C_prime: 56,
    D_prime: 291,
    monthlyA: { '11月': 803, '12月': 800 },
  },
  {
    no: 55,
    majorCategory: '情報通信業',
    mediumCategory: '情報サービス業',
    minorCategory: 'ソフトウェア業',
    A: 825,
    B_prime: 9.7,
    C_prime: 56,
    D_prime: 284,
    monthlyA: { '11月': 844, '12月': 845 },
  },
  {
    no: 56,
    majorCategory: '情報通信業',
    mediumCategory: '情報サービス業',
    minorCategory: '情報処理・提供サービス業',
    A: 679,
    B_prime: 8.8,
    C_prime: 48,
    D_prime: 246,
    monthlyA: { '11月': 662, '12月': 640 },
  },
  {
    no: 57,
    majorCategory: '情報通信業',
    mediumCategory: 'インターネット附随サービス業',
    minorCategory: '（全体）',
    A: 618,
    B_prime: 6.7,
    C_prime: 37,
    D_prime: 207,
    monthlyA: { '11月': 577, '12月': 576 },
  },
  {
    no: 58,
    majorCategory: '情報通信業',
    mediumCategory: '映像・音声・文字情報制作業',
    minorCategory: '（全体）',
    A: 506,
    B_prime: 4.3,
    C_prime: 41,
    D_prime: 286,
    monthlyA: { '11月': 531, '12月': 585 },
  },
  {
    no: 59,
    majorCategory: '情報通信業',
    mediumCategory: 'その他の情報通信業',
    minorCategory: '（全体）',
    A: 696,
    B_prime: 11.6,
    C_prime: 61,
    D_prime: 612,
    monthlyA: { '11月': 663, '12月': 652 },
  },
  // 運輸業、郵便業
  {
    no: 60,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 305,
    B_prime: 7.7,
    C_prime: 62,
    D_prime: 465,
    monthlyA: { '11月': 322, '12月': 331 },
  },
  {
    no: 61,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '道路貨物運送業',
    minorCategory: '（全体）',
    A: 291,
    B_prime: 6.3,
    C_prime: 48,
    D_prime: 411,
    monthlyA: { '11月': 308, '12月': 313 },
  },
  {
    no: 62,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '水運業',
    minorCategory: '（全体）',
    A: 335,
    B_prime: 19.9,
    C_prime: 166,
    D_prime: 576,
    monthlyA: { '11月': 358, '12月': 387 },
  },
  {
    no: 63,
    majorCategory: '運輸業、郵便業',
    mediumCategory: '運輸に附帯するサービス業',
    minorCategory: '（全体）',
    A: 262,
    B_prime: 5.6,
    C_prime: 44,
    D_prime: 488,
    monthlyA: { '11月': 267, '12月': 276 },
  },
  {
    no: 64,
    majorCategory: '運輸業、郵便業',
    mediumCategory: 'その他の運輸業、郵便業',
    minorCategory: '（全体）',
    A: 345,
    B_prime: 5.1,
    C_prime: 43,
    D_prime: 449,
    monthlyA: { '11月': 368, '12月': 373 },
  },
  // 卸売業
  {
    no: 65,
    majorCategory: '卸売業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 399,
    B_prime: 9.1,
    C_prime: 57,
    D_prime: 442,
    monthlyA: { '11月': 421, '12月': 425 },
  },
  {
    no: 66,
    majorCategory: '卸売業',
    mediumCategory: '各種商品卸売業',
    minorCategory: '（全体）',
    A: 494,
    B_prime: 15.5,
    C_prime: 92,
    D_prime: 535,
    monthlyA: { '11月': 560, '12月': 546 },
  },
  {
    no: 67,
    majorCategory: '卸売業',
    mediumCategory: '繊維・衣服等卸売業',
    minorCategory: '（全体）',
    A: 247,
    B_prime: 6.9,
    C_prime: 26,
    D_prime: 518,
    monthlyA: { '11月': 270, '12月': 274 },
  },
  {
    no: 68,
    majorCategory: '卸売業',
    mediumCategory: '飲食料品卸売業',
    minorCategory: '（全体）',
    A: 353,
    B_prime: 4.8,
    C_prime: 40,
    D_prime: 333,
    monthlyA: { '11月': 407, '12月': 405 },
  },
  {
    no: 69,
    majorCategory: '卸売業',
    mediumCategory: '飲食料品卸売業',
    minorCategory: '農畜産物・水産物卸売業',
    A: 196,
    B_prime: 3.0,
    C_prime: 28,
    D_prime: 263,
    monthlyA: { '11月': 208, '12月': 209 },
  },
  {
    no: 70,
    majorCategory: '卸売業',
    mediumCategory: '飲食料品卸売業',
    minorCategory: '食料・飲料卸売業',
    A: 502,
    B_prime: 6.5,
    C_prime: 52,
    D_prime: 400,
    monthlyA: { '11月': 596, '12月': 591 },
  },
  {
    no: 71,
    majorCategory: '卸売業',
    mediumCategory: '建築材料、鉱物・金属材料等卸売業',
    minorCategory: '（全体）',
    A: 377,
    B_prime: 10.9,
    C_prime: 70,
    D_prime: 536,
    monthlyA: { '11月': 393, '12月': 408 },
  },
  {
    no: 72,
    majorCategory: '卸売業',
    mediumCategory: '建築材料、鉱物・金属材料等卸売業',
    minorCategory: '化学製品卸売業',
    A: 459,
    B_prime: 14.1,
    C_prime: 78,
    D_prime: 665,
    monthlyA: { '11月': 470, '12月': 486 },
  },
  {
    no: 73,
    majorCategory: '卸売業',
    mediumCategory: '建築材料、鉱物・金属材料等卸売業',
    minorCategory: 'その他の建築材料、鉱物・金属材料等卸売業',
    A: 358,
    B_prime: 10.2,
    C_prime: 68,
    D_prime: 507,
    monthlyA: { '11月': 375, '12月': 391 },
  },
  {
    no: 74,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: '（全体）',
    A: 458,
    B_prime: 10.8,
    C_prime: 64,
    D_prime: 473,
    monthlyA: { '11月': 475, '12月': 481 },
  },
  {
    no: 75,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: '産業機械器具卸売業',
    A: 447,
    B_prime: 8.6,
    C_prime: 56,
    D_prime: 464,
    monthlyA: { '11月': 474, '12月': 482 },
  },
  {
    no: 76,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: '電気機械器具卸売業',
    A: 472,
    B_prime: 12.0,
    C_prime: 69,
    D_prime: 481,
    monthlyA: { '11月': 473, '12月': 475 },
  },
  {
    no: 77,
    majorCategory: '卸売業',
    mediumCategory: '機械器具卸売業',
    minorCategory: 'その他の機械器具卸売業',
    A: 446,
    B_prime: 12.1,
    C_prime: 67,
    D_prime: 470,
    monthlyA: { '11月': 478, '12月': 492 },
  },
  {
    no: 78,
    majorCategory: '卸売業',
    mediumCategory: 'その他の卸売業',
    minorCategory: '（全体）',
    A: 370,
    B_prime: 7.0,
    C_prime: 48,
    D_prime: 342,
    monthlyA: { '11月': 374, '12月': 373 },
  },
  // 小売業
  {
    no: 79,
    majorCategory: '小売業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 456,
    B_prime: 6.8,
    C_prime: 43,
    D_prime: 310,
    monthlyA: { '11月': 469, '12月': 477 },
  },
  {
    no: 80,
    majorCategory: '小売業',
    mediumCategory: '各種商品小売業',
    minorCategory: '（全体）',
    A: 280,
    B_prime: 3.5,
    C_prime: 26,
    D_prime: 288,
    monthlyA: { '11月': 284, '12月': 283 },
  },
  {
    no: 81,
    majorCategory: '小売業',
    mediumCategory: '織物・衣服・身の回り品小売業',
    minorCategory: '（全体）',
    A: 738,
    B_prime: 9.5,
    C_prime: 66,
    D_prime: 351,
    monthlyA: { '11月': 736, '12月': 759 },
  },
  {
    no: 82,
    majorCategory: '小売業',
    mediumCategory: '飲食料品小売業',
    minorCategory: '（全体）',
    A: 355,
    B_prime: 5.5,
    C_prime: 33,
    D_prime: 286,
    monthlyA: { '11月': 374, '12月': 379 },
  },
  {
    no: 83,
    majorCategory: '小売業',
    mediumCategory: '機械器具小売業',
    minorCategory: '（全体）',
    A: 339,
    B_prime: 8.5,
    C_prime: 54,
    D_prime: 337,
    monthlyA: { '11月': 337, '12月': 336 },
  },
  {
    no: 84,
    majorCategory: '小売業',
    mediumCategory: 'その他の小売業',
    minorCategory: '（全体）',
    A: 540,
    B_prime: 7.5,
    C_prime: 45,
    D_prime: 345,
    monthlyA: { '11月': 577, '12月': 595 },
  },
  {
    no: 85,
    majorCategory: '小売業',
    mediumCategory: 'その他の小売業',
    minorCategory: '医薬品・化粧品小売業',
    A: 756,
    B_prime: 7.6,
    C_prime: 58,
    D_prime: 395,
    monthlyA: { '11月': 814, '12月': 836 },
  },
  {
    no: 86,
    majorCategory: '小売業',
    mediumCategory: 'その他の小売業',
    minorCategory: 'その他の小売業',
    A: 458,
    B_prime: 7.5,
    C_prime: 40,
    D_prime: 329,
    monthlyA: { '11月': 484, '12月': 500 },
  },
  {
    no: 87,
    majorCategory: '小売業',
    mediumCategory: '無店舗小売業',
    minorCategory: '（全体）',
    A: 356,
    B_prime: 4.0,
    C_prime: 30,
    D_prime: 191,
    monthlyA: { '11月': 336, '12月': 326 },
  },
  // 金融業、保険業
  {
    no: 88,
    majorCategory: '金融業、保険業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 266,
    B_prime: 5.7,
    C_prime: 35,
    D_prime: 266,
    monthlyA: { '11月': 289, '12月': 289 },
  },
  {
    no: 89,
    majorCategory: '金融業、保険業',
    mediumCategory: '銀行業',
    minorCategory: '（全体）',
    A: 92,
    B_prime: 2.7,
    C_prime: 18,
    D_prime: 247,
    monthlyA: { '11月': 105, '12月': 103 },
  },
  {
    no: 90,
    majorCategory: '金融業、保険業',
    mediumCategory: '金融商品取引業、商品先物取引業',
    minorCategory: '（全体）',
    A: 312,
    B_prime: 7.5,
    C_prime: 59,
    D_prime: 292,
    monthlyA: { '11月': 345, '12月': 351 },
  },
  {
    no: 91,
    majorCategory: '金融業、保険業',
    mediumCategory: 'その他の金融業、保険業',
    minorCategory: '（全体）',
    A: 585,
    B_prime: 10.3,
    C_prime: 50,
    D_prime: 283,
    monthlyA: { '11月': 616, '12月': 618 },
  },
  // 不動産業、物品賃貸業
  {
    no: 92,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 363,
    B_prime: 7.5,
    C_prime: 48,
    D_prime: 314,
    monthlyA: { '11月': 379, '12月': 389 },
  },
  {
    no: 93,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '不動産取引業',
    minorCategory: '（全体）',
    A: 265,
    B_prime: 6.5,
    C_prime: 47,
    D_prime: 262,
    monthlyA: { '11月': 280, '12月': 275 },
  },
  {
    no: 94,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '不動産賃貸業・管理業',
    minorCategory: '（全体）',
    A: 455,
    B_prime: 8.0,
    C_prime: 42,
    D_prime: 331,
    monthlyA: { '11月': 471, '12月': 491 },
  },
  {
    no: 95,
    majorCategory: '不動産業、物品賃貸業',
    mediumCategory: '物品賃貸業',
    minorCategory: '（全体）',
    A: 519,
    B_prime: 10.4,
    C_prime: 65,
    D_prime: 422,
    monthlyA: { '11月': 532, '12月': 558 },
  },
  // 専門・技術サービス業（令和6年は技術サービス業の小分類なし）
  {
    no: 96,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 456,
    B_prime: 6.6,
    C_prime: 42,
    D_prime: 212,
    monthlyA: { '11月': 420, '12月': 424 },
  },
  {
    no: 97,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '専門サービス業',
    minorCategory: '（全体）',
    A: 805,
    B_prime: 10.8,
    C_prime: 52,
    D_prime: 227,
    monthlyA: { '11月': 725, '12月': 737 },
  },
  {
    no: 98,
    majorCategory: '専門・技術サービス業',
    mediumCategory: '広告業',
    minorCategory: '（全体）',
    A: 416,
    B_prime: 6.0,
    C_prime: 48,
    D_prime: 217,
    monthlyA: { '11月': 380, '12月': 374 },
  },
  // 宿泊業、飲食サービス業
  {
    no: 99,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 514,
    B_prime: 3.4,
    C_prime: 25,
    D_prime: 165,
    monthlyA: { '11月': 563, '12月': 561 },
  },
  {
    no: 100,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: '（全体）',
    A: 521,
    B_prime: 3.4,
    C_prime: 22,
    D_prime: 150,
    monthlyA: { '11月': 585, '12月': 583 },
  },
  {
    no: 101,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: '食堂、レストラン（専門料理店を除く）',
    A: 290,
    B_prime: 1.1,
    C_prime: 14,
    D_prime: 80,
    monthlyA: { '11月': 317, '12月': 330 },
  },
  {
    no: 102,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: '専門料理店',
    A: 664,
    B_prime: 5.0,
    C_prime: 28,
    D_prime: 174,
    monthlyA: { '11月': 750, '12月': 747 },
  },
  {
    no: 103,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: '飲食店',
    minorCategory: 'その他の飲食店',
    A: 449,
    B_prime: 2.6,
    C_prime: 17,
    D_prime: 149,
    monthlyA: { '11月': 504, '12月': 497 },
  },
  {
    no: 104,
    majorCategory: '宿泊業、飲食サービス業',
    mediumCategory: 'その他の宿泊業、飲食サービス業',
    minorCategory: '（全体）',
    A: 490,
    B_prime: 3.5,
    C_prime: 36,
    D_prime: 223,
    monthlyA: { '11月': 482, '12月': 479 },
  },
  // 生活関連サービス業、娯楽業
  {
    no: 105,
    majorCategory: '生活関連サービス業、娯楽業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 904,
    B_prime: 6.7,
    C_prime: 46,
    D_prime: 303,
    monthlyA: { '11月': 871, '12月': 876 },
  },
  {
    no: 106,
    majorCategory: '生活関連サービス業、娯楽業',
    mediumCategory: '生活関連サービス業',
    minorCategory: '（全体）',
    A: 434,
    B_prime: 4.5,
    C_prime: 36,
    D_prime: 227,
    monthlyA: { '11月': 427, '12月': 428 },
  },
  {
    no: 107,
    majorCategory: '生活関連サービス業、娯楽業',
    mediumCategory: '娯楽業',
    minorCategory: '（全体）',
    A: 1586,
    B_prime: 9.8,
    C_prime: 61,
    D_prime: 413,
    monthlyA: { '11月': 1514, '12月': 1526 },
  },
  // 教育、学習支援業
  {
    no: 108,
    majorCategory: '教育、学習支援業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 523,
    B_prime: 9.5,
    C_prime: 42,
    D_prime: 218,
    monthlyA: { '11月': 488, '12月': 470 },
  },
  // 医療、福祉
  {
    no: 109,
    majorCategory: '医療、福祉',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 601,
    B_prime: 7.5,
    C_prime: 48,
    D_prime: 257,
    monthlyA: { '11月': 556, '12月': 555 },
  },
  // サービス業（他に分類されないもの）
  {
    no: 110,
    majorCategory: 'サービス業（他に分類されないもの）',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 1019,
    B_prime: 16.2,
    C_prime: 91,
    D_prime: 417,
    monthlyA: { '11月': 994, '12月': 1043 },
  },
  {
    no: 111,
    majorCategory: 'サービス業（他に分類されないもの）',
    mediumCategory: '職業紹介・労働者派遣業',
    minorCategory: '（全体）',
    A: 1198,
    B_prime: 15.6,
    C_prime: 105,
    D_prime: 405,
    monthlyA: { '11月': 1226, '12月': 1260 },
  },
  {
    no: 112,
    majorCategory: 'サービス業（他に分類されないもの）',
    mediumCategory: 'その他の事業サービス業',
    minorCategory: '（全体）',
    A: 894,
    B_prime: 16.6,
    C_prime: 82,
    D_prime: 425,
    monthlyA: { '11月': 833, '12月': 891 },
  },
  // その他の産業
  {
    no: 113,
    majorCategory: 'その他の産業',
    mediumCategory: '（全体）',
    minorCategory: '（全体）',
    A: 473,
    B_prime: 8.0,
    C_prime: 46,
    D_prime: 348,
    monthlyA: { '11月': 482, '12月': 487 },
  },
]

// ============================================================
// 令和5年分（2023年）- 主要業種のみ（全データは国税庁から追加が必要）
// 出典: https://www.nta.go.jp/law/tsutatsu/kobetsu/hyoka/r05/2306/index.htm
// ============================================================
const reiwa5Data: SimilarIndustryDataRow[] = [
  {
    no: 3,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: '建築工事業（木造建築工事業を除く）',
    A: 339,
    B_prime: 9.9,
    C_prime: 72,
    D_prime: 432,
  },
  {
    no: 4,
    majorCategory: '建設業',
    mediumCategory: '総合工事業',
    minorCategory: 'その他の総合工事業',
    A: 251,
    B_prime: 7.6,
    C_prime: 41,
    D_prime: 384,
  },
  {
    no: 12,
    majorCategory: '製造業',
    mediumCategory: '食料品製造業',
    minorCategory: '畜産食料品製造業',
    A: 988,
    B_prime: 10.6,
    C_prime: 73,
    D_prime: 518,
  },
]

export const similarIndustryDatabase: SimilarIndustryDatabase = {
  令和7年: reiwa7Data,
  令和6年: reiwa6Data,
  令和5年: reiwa5Data,
}
